export type Product={id:number;name:string;category:string;price:string;image:string;alt:string;gallery:string[];description:string;details:string[]};
export const products:Product[]=[
{id:1,name:'Sculpted Wool Coat',category:'Outerwear',price:'€1,290',image:'/images/noire-product-coat.svg',alt:'Model in sculptural black coat',gallery:['/images/noire-product-coat.svg','/images/noire-feature-2.svg','/images/noire-feature-1.svg'],description:'A sculptural wool coat cut with quiet authority. A precise shoulder, fluid fall and considered volume define the silhouette.',details:['90% virgin wool · 10% cashmere','Relaxed architectural fit','Made in Italy','Dry clean only']},
{id:2,name:'No. 07 Silk Dress',category:'Dresses',price:'€890',image:'/images/noire-product-dress.svg',alt:'Editorial black fashion dress',gallery:['/images/noire-product-dress.svg','/images/noire-editorial.svg','/images/noire-story.svg'],description:'Fluid silk with a disciplined line. No. 07 moves between evening and everyday with deliberate ease.',details:['100% silk','Bias-cut silhouette','Made in Portugal','Professional clean recommended']},
{id:3,name:'Atelier Leather Bag',category:'Accessories',price:'€640',image:'/images/noire-product-bag.svg',alt:'Luxury leather handbag',gallery:['/images/noire-product-bag.svg','/images/noire-product-bag.svg','/images/noire-product-bag.svg'],description:'A structured everyday companion in supple leather, finished with restrained hardware and an architectural profile.',details:['Full-grain leather','Cotton twill lining','Hand-finished edges','Made in Spain']},
{id:4,name:'Tailored Trousers',category:'Tailoring',price:'€520',image:'/images/noire-product-trousers.svg',alt:'Tailored fashion trousers',gallery:['/images/noire-product-trousers.svg','/images/noire-product-jacket.svg','/images/noire-product-coat.svg'],description:'A clean trouser with an elongated line and soft structure, designed to anchor the modern wardrobe.',details:['Wool blend','High-rise tailored waist','Straight leg','Made in Portugal']},
{id:5,name:'The Column Jacket',category:'Tailoring',price:'€980',image:'/images/noire-product-jacket.svg',alt:'Minimal tailored jacket',gallery:['/images/noire-product-jacket.svg',img('1594633312681-425c7b97ccd1',1200),img('1483985988355-763728e1935b',1200)],description:'A refined jacket built around a long columnar silhouette, balancing structure with movement.',details:['Wool suiting','Soft shoulder construction','Two internal pockets','Made in Italy']},
{id:6,name:'Luna Leather Heel',category:'Shoes',price:'€590',image:'/images/noire-product-heel.svg',alt:'Black leather heels',gallery:['/images/noire-product-heel.svg','/images/noire-product-dress.svg','/images/noire-product-bag.svg'],description:'A sculpted heel with a clean architectural curve. Quiet from a distance, unmistakable up close.',details:['Nappa leather upper','Leather sole','70mm heel','Made in Italy']}
];
export const navItems=['Shop','Collections','Journal','About'];