export type Product={id:string;name:string;category:string;price:string;image:string;alt:string;gallery:string[];description:string;details:string[];stock?:number;sizes?:string[];colors?:string[];colorImages?:Record<string,string>};
export const products:Product[]=[
{id:'sculpted-wool-coat',name:'Sculpted Wool Coat',category:'Outerwear',price:'€1,290',image:'/images/noire-coat.jpg',alt:'Model in sculptural black coat',gallery:['/images/noire-coat.jpg','/images/noire-editorial.jpg','/images/noire-story.jpg'],description:'A sculptural wool coat cut with quiet authority. A precise shoulder, fluid fall and considered volume define the silhouette.',details:['90% virgin wool · 10% cashmere','Relaxed architectural fit','Made in Italy','Dry clean only']},
{id:'no-07-silk-dress',name:'No. 07 Silk Dress',category:'Dresses',price:'€890',image:'/images/noire-dress.jpg',alt:'Editorial black fashion dress',gallery:['/images/noire-dress.jpg','/images/noire-editorial.jpg','/images/noire-story.jpg'],description:'Fluid silk with a disciplined line. No. 07 moves between evening and everyday with deliberate ease.',details:['100% silk','Bias-cut silhouette','Made in Portugal','Professional clean recommended']},
{id:'atelier-leather-bag',name:'Atelier Leather Bag',category:'Accessories',price:'€640',image:'/images/noire-bag.jpg',alt:'Luxury leather handbag',gallery:['/images/noire-bag.jpg','/images/noire-editorial.jpg','/images/noire-story.jpg'],description:'A structured everyday companion in supple leather, finished with restrained hardware and an architectural profile.',details:['Full-grain leather','Cotton twill lining','Hand-finished edges','Made in Spain']},
{id:'tailored-trousers',name:'Tailored Trousers',category:'Tailoring',price:'€520',image:'/images/noire-trousers.jpg',alt:'Tailored fashion trousers',gallery:['/images/noire-trousers.jpg','/images/noire-jacket.jpg','/images/noire-coat.jpg'],description:'A clean trouser with an elongated line and soft structure, designed to anchor the modern wardrobe.',details:['Wool blend','High-rise tailored waist','Straight leg','Made in Portugal']},
{id:'column-jacket',name:'The Column Jacket',category:'Tailoring',price:'€980',image:'/images/noire-jacket.jpg',alt:'Minimal tailored jacket',gallery:['/images/noire-jacket.jpg','/images/noire-editorial.jpg','/images/noire-story.jpg'],description:'A refined jacket built around a long columnar silhouette, balancing structure with movement.',details:['Wool suiting','Soft shoulder construction','Two internal pockets','Made in Italy']},
{id:'luna-leather-heel',name:'Luna Leather Heel',category:'Shoes',price:'€590',image:'/images/noire-heel.jpg',alt:'Black leather heels',gallery:['/images/noire-heel.jpg','/images/noire-dress.jpg','/images/noire-bag.jpg'],description:'A sculpted heel with a clean architectural curve. Quiet from a distance, unmistakable up close.',details:['Nappa leather upper','Leather sole','70mm heel','Made in Italy']}
];
export const navItems=['Shop','Collections','Journal','About'];